### ISSUE TITLE
Połączenie dostęp do stanowiska + stanowiska

### ISSUE THREAD

**Issue by JacobPi42** [JAck0b/Klinika#12]

**Comment by JAck0b** [comment]
Już wieim po co zrobiłem tę tabelę dostęp_do_stanowiska. Jak jest na przykład salka gimnastyczne, to tam ma dostęp tak z 5 specjalizacji i podobnie jest z łóżkami rehabilitacyjnymi. I na przykład każde jedno łóżko występowałoby tam z 4 razy dla przykładu. Teraz to nie wiem za bardzo co robić, bo jak coś zmienię to będą się mega powtarzać i jak jest 295 stanowisk, to dotępów będzie około 400. Co robić?

**Comment by JAck0b** [comment]
Tak z dwojga złego, to chyba lepiej zostawić tę tabelę, i zmienię po prostu nazwę na ID uprawnień.

**Comment by JAck0b** [comment]
To jest już zrobione i zakomentowane. Byłbym bardzo wdzięczny jakbyś sprawdził, czy to naprawdę działa.

**Comment by JacobPi42** [comment]
ok sprawdzę
